language: php
dist: trusty
sudo: false
php: 7.2

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

branches:
  only:
    - 3.x

mysql:
  database: thunder
  username: root
  encoding: utf8

before_install:
  - source ./scripts/travis/01-setup-environment.sh

script:
# Installing thunder is the actual test
  - bash -x -e ./scripts/travis/02-install-thunder.sh
