name: Run thunder-develop tests

on:
  pull_request:
    branches:
      - 3.x

  schedule:
    - cron:  '0 7 * * *'

jobs:

  test:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '7.4'
          extensions: Imagick
          tools: composer:v1

      - name: Start MySql service
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Install dependencies
        run: |
          composer install

      - name: Install Thunder
        run: |
          cd docroot
          /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush si thunder --db-url=mysql://root:root@127.0.0.1/thunder -y -vvv
