name: Run distribution tests

on:
  pull_request:
    branches:
      - 3.x

  schedule:
    - cron:  '0 7 * * *'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '7.4'
          extensions: Imagick
          tools: composer:v1

      - name: Start MySql service
        run: |
          sudo /etc/init.d/mysql start

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-cache-

      - name: Get build environment
        run: |
          bash -x -e ./scripts/travis/02-install-thunder.sh

